### ISSUE TITLE
"Undefined Index:" error when trying to use bundle

### ISSUE THREAD

**Issue by saintwolf** [anacona16/DependentFormsBundle#1]
Hi,

I have set up the bundle as per the installation guide for multi-level dependent forms, however I am getting an "Undefined Index:" error.

Here are the details:

An exception has been thrown during the rendering of a template ("Notice: Undefined index: ") in DependentFormsBundle:Form:fields.html.twig at line 11.

> [1/2] ContextErrorException: Notice: Undefined index:
> 
> in vendor/symfony/symfony/src/Symfony/Component/Form/FormView.php at line 108   -

```
     */
    public function offsetGet($name)
    {
        return $this->children[$name];
    }
```

> [2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Notice: Undefined index: ") in DependentFormsBundle:Form:fields.html.twig at line 11.
> 
> in vendor/twig/twig/lib/Twig/Template.php at line 182   -
> 
> ```
>                 throw $e;
>             } catch (Exception $e) {
>                 throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $template->getTemplateName(), $e);
>             }
>         } elseif (false !== $parent = $this->getParent($context)) {
>             $parent->displayBlock($name, $context, array_merge($this->blocks, $blocks), false);
> ```

**Comment by anacona16** [comment]
I've replicated your bug, but it is not a bug. Probably you forgot to add the **_parent_field_** property in one of the fields.

Can you paste your form code here, please?
