### ISSUE TITLE
Compatibility with sonata admin

### ISSUE THREAD

**Issue by princelionelnzi** [anacona16/DependentFormsBundle#2]
Hello Thanks for this project. I want to use it for a personal project but I am facing an issue when combining it with Sonata Admin.

![21469848_1269116333198185_663090334_n](https://user-images.githubusercontent.com/16304369/30163160-71e40380-93c7-11e7-9ad1-067baa113569.png)

After following your documentation of the implementation, I was able to create the dependencies between the various forms. But the issue is that I get 2 fields for each form as shown on the image. Is there a way to solve it ?

**Comment by anacona16** [comment]
Hi @princelionelnzi this bundle is already compatible with sonata admin bundle. I had the same problem as you and I resolved it doing this:

```javascript
$(document).ajaxSuccess(function (event, xhr, settings) {
    Admin.setup_select2();
});
```

Paste that code in your layout.

**Comment by princelionelnzi** [comment]
Thanks
